import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "./auth/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="home-main">
        <section className="hero-section">
          <h2>HOME</h2>
        </section>
      </main>
    </>
  );
}
